services:
  server:
    build: .
    ports:
      - "9000:9000"
    depends_on:
      - redis
    environment:
      - MONGODB_URI=mongodb+srv://shradesh71:newone71@cluster0.4tegtua.mongodb.net/spring
  worker:
    build: .
    command: ["node", "workers/worker.js"]
    depends_on:
      - redis
    environment:
      - MONGODB_URI=mongodb+srv://shradesh71:newone71@cluster0.4tegtua.mongodb.net/spring
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./config/prometheus-config.yml:/etc/prometheus/prometheus.yml
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    depends_on:
      - prometheus
      - loki
    ports:
      - "3000:3000"

  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
